### ISSUE TITLE
Integrate SSM agent to run EKS log collector without SSH'ing into the Worker Node. 

### ISSUE THREAD

**Issue by nithu0115** [nithu0115/eks-logs-collector#6]
Requirements: 

- [x] Need SSM agent baked into the AMI. 
- [x] Need a SSM Document 
- [x] Node Instance Role requires IAM policy/permissions to push S3 bucket
- [x] Update Readme

**Comment by hugoprudente** [comment]
This would be a nice improvement for nodes that does not have SSH keys, nice work man!

**Comment by nithu0115** [comment]
Closing this issue in favor or #13
